hello honey bunny

In [1]:
import numpy as np

In [2]:
arr =np.arange(100000000)

In [3]:
pythlist=list(range(100000000))

In [4]:
np.array([3,5,6,7,8,9])

array([3, 5, 6, 7, 8, 9])

In [5]:
array1 = np.array([[1,2,3,4,5],[34,5,6,7,9]])
print(type(array1))

<class 'numpy.ndarray'>


In [6]:
array1.shape

(2, 5)

In [7]:
array1

array([[ 1,  2,  3,  4,  5],
       [34,  5,  6,  7,  9]])

In [8]:
array1+array1

array([[ 2,  4,  6,  8, 10],
       [68, 10, 12, 14, 18]])

In [9]:
1/array1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.02941176, 0.2       , 0.16666667, 0.14285714, 0.11111111]])

In [10]:
array1*array1

array([[   1,    4,    9,   16,   25],
       [1156,   25,   36,   49,   81]])

In [11]:
np.empty((4,4),dtype='float')

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219578e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [12]:
array1

array([[ 1,  2,  3,  4,  5],
       [34,  5,  6,  7,  9]])

In [13]:
array2 = np.array([1,2,3,4,5,6,7,8,9])

In [14]:
arr = array2[4:6].copy()

In [15]:
arr

array([5, 6])

In [16]:
arr[0] = 9

In [17]:
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr

array([9, 6])

In [19]:
array1

array([[ 1,  2,  3,  4,  5],
       [34,  5,  6,  7,  9]])

In [20]:
array1[0]

array([1, 2, 3, 4, 5])

In [21]:
array1[0,0:4] = 0

In [22]:
array1

array([[ 0,  0,  0,  0,  5],
       [34,  5,  6,  7,  9]])